### ISSUE TITLE
App crashes when user is deleted

### ISSUE THREAD

**Issue by vilgovskiy** [kyttndr/Back-On-Rails#13]
When user is deleted, app redirects to: `"users_path"`, but when the page is rendered, it calls `:set_user` function that executes:
`@user = User.find(params[:user_id])`

but delete user option is only available to the user himself, which after deletion causes id of deleted user to be passed and then lookup on this id happens in `:set_user`, which causes an error.

**Comment by vilgovskiy** [comment]
Looks like it happens due to sessions

**Comment by intermofel** [comment]
fixed
